### ISSUE TITLE
Problem with sampling

### ISSUE THREAD

**Issue by AlbertoJaenal** [janinethoma/image_navigation_python#1]
Hi, Janine

I've tried the code just running `demo.py` and everything goes fine.
Then, just to check the sampling, I renamed the `temp.pickle` and rerun the demo.

Then, this error arised:

```
  File "demo_COLD.py", line 191, in <module>
    main()
  File "demo_COLD.py", line 135, in main
    flow_lm = sample_with_flow(ref['xy'], edges, source_idx, sink_idx, geo_dists, feat_dists, num_landmarks)
  File ..., line 103, in sample_with_flow
    M.constraint(stack, mf.Domain.inRotatedQCone().axis(2))  # Each row is in a rotated quadratic cone
  File "/usr/local/lib/python3.7/dist-packages/mosek/fusion/impl/_implementation.py", line 3554, in constraint
    return self._constraint_Lmosek_4fusion_4Expression_2Lmosek_4fusion_4ConeDomain_2(*args)
  File "/usr/local/lib/python3.7/dist-packages/mosek/fusion/impl/_implementation.py", line 6184, in _constraint_Lmosek_4fusion_4Expression_2Lmosek_4fusion_4ConeDomain_2
    return (self.__constraint_1_SLmosek_4fusion_4Expression_2Lmosek_4fusion_4ConeDomain_2("",_0,_1))
  File "/usr/local/lib/python3.7/dist-packages/mosek/fusion/impl/_implementation.py", line 7668, in __constraint_1_SLmosek_4fusion_4Expression_2Lmosek_4fusion_4ConeDomain_2
    _22=_19[_21]
IndexError: index 2 is out of bounds for axis 0 with size 2

```

The trouble line was the line 103 in `sample_with_flow.py`:
`    M.constraint(stack, mf.Domain.inRotatedQCone().axis(2))  # Each row is in a rotated quadratic cone`

Checking the dimensions of the variable `stack`, its shape is `[898588,      3]`.
So, to solve the problem, I think you have to set:

`    M.constraint(stack, mf.Domain.inRotatedQCone().axis(**1**))  # Each row is in a rotated quadratic cone`

Regards

**Comment by janinethoma** [comment]
Hi Alberto,

Thank you for pointing this out. Did you use a newer mosek version than 8.1.80? When I tested the repo with Python 3.5.5 and mosek 8.1.80 in the past it used to run without errors. Testing with Python 3.8 and mosek 9.2.29, however, reproduces your error. In this case, your suggested solution does solve the problem. I am updating the repo to work with Python 3.8 and mosek 9.2.29.

Best regards,
Janine

**Comment by AlbertoJaenal** [comment]
Yeah, there was the problem. I'm using too Python 3.7 and Mosek 9.2.29.
Thanks. Best regards,
Alberto
